const mongoose=require('mongoose');
const userSchema=new mongoose.Schema({
username:{
  type:String,
  required:true
},
email:{
  type:String,
  required:true
},
role:{
  type:String,
  required:true,
  enum:["admin","user"],
  default:"user"
},
password:{
  type:String,
  required:true
},
lastlogin:{
  type:Date,
  default:Date.now()
},
isVerified:{
  type:Boolean,
  default:false,
},

accountLevel:{
  type:String,
  enum:["bronze","silver","gold"],
  default:"bronze"
},
profilePicture:{
  type:String,
  default:""
},
coverImage:{
  type:String,
  default:""
},
bio:{
  type:String,
},
location:{
  type:String,
},
notificationType:{
  email:{
    type:String,
    required:true
  }
},
gender:{
  type:String,
  enum:["male","female","prefer not to say"]
},
profileViewers:[{type:mongoose.Schema.Types.ObjectId,ref:"User"}],
followers:[{type:mongoose.Schema.ObjectId,ref:"User"}],
following:[{type:mongoose.Schema.ObjectId,ref:"User"}],
blockUsers:[{type:mongoose.Schema.ObjectId,ref:"User"}],
posts:[{type:mongoose.Schema.ObjectId,ref:"Post"}],
likedPosts:[{type:mongoose.Schema.ObjectId,ref:"Post"}],
passwordResetToken:{
  type:String,
},
passwordResetExpires:{
type:Date
},
accountVerificationToken:{
  type:String
},
accountVerificationExpires:{
  type:Date
}
},{timestamps:true});
//schema to model
const User=mongoose.model("User",userSchema);
module.exports=User;